### ISSUE TITLE
Give the Privacydev instance the option to switch from SFW to N4 or O2

### ISSUE THREAD

**Issue by BuriGoki** [PrivacyDevel/nitter#24]
Can you give the Privacydev instance the option to switch from SFW to N4 or O2?

**Comment by PrivacyDevel** [comment]
Not directly, no. There is a very small number of requests that you are allowed to make with those NSFW instances at any given time. Every other requests falls back to the SFW Backup. I am forced to do this because of Twitter's account based rate limiting. I don't want a single person or bot to use up all of those requests for themselves.

I have been thinking about implementing a mechanism that allows you to decide when you want to use your "NSFW quota" manually before but am not sure how exactly I would implement it.

You will most likely unfortunately have to live with that, if you want to use my instance until I have more accounts.

**Comment by ultrajae** [comment]
Thank you for keeping this up any way you can.

Any idea why more haven't implemented your patch, or why it hasn't been mainlined?

**Comment by PrivacyDevel** [comment]
With the use of guest accounts this should no longer be an issue for now.
