### ISSUE TITLE
with_replies also fetching people who replied to tweets

### ISSUE THREAD

**Issue by roryyamm** [PrivacyDevel/nitter#8]
Not sure if this is specific to this fork, or Nitter in general, but it only occurs when on the privacydev.net instance. 

When using the /with_replies page, sometimes people who replied to the user in question get presented alongside that user's own replies, retweets, and normal tweets. This also shows up in the RSS feeds of said page, leading to an RSS feed full of random people. This is not desirable.

**Comment by PrivacyDevel** [comment]
This may have been introduced in [graphql-missing-threads-bug-fix](https://github.com/PrivacyDevel/nitter/tree/graphql-missing-threads-bug-fix) / 1634ffdf43c1d9351b7d02103061baa8fa247fd6.
ping https://github.com/zedeus/nitter/pull/885

**Comment by zedeus** [comment]
Found an example here:
![image](https://github.com/PrivacyDevel/nitter/assets/9434921/8e1a26ad-1736-4d1f-8fcc-ab66472fd9c1)

It's probably caused by the automatic threading Nitter performs, not sure how it should work here.

**Comment by roryyamm** [comment]
@zedeus would it be possible to disable threading for RSS feeds?

**Comment by pin-grid-array** [comment]
> @zedeus would it be possible to disable threading for RSS feeds?

This is the solution.

I noticed that these two instances are not affected by the bug described by roryyamm:
https://nitter.caioalonso.com/MarkHamill/with_replies/rss
https://nitter.privacytools.io/MarkHamill/with_replies/rss

What do these two instances have in common? They do not show threading in `with_replies`, except when the user replies to themselves.

I made a small list of instances that *are* affected by the bug in [this post](https://github.com/zedeus/nitter/issues/893#issue-1736318127). (The instance nitter.privacydev.net is one of several affected.) What do all of those instances have in common? They all show threading in `with_replies`.

So, disabling threading appears to be the correct solution.

In that same post, I also made a small list of instances that are not affected by the bug but whose `with_replies/rss` feed is completely broken by not showing any replies at all. At first, I thought it was related to the bug, but after reading this thread and learning that the problem is caused by threading, maybe it is not related after all.

**Comment by zedeus** [comment]
It's broken because they don't use the new-ish GraphQL API that remotely up-to-date Nitter instances use. Disabling threading is not a solution, it's just a temporary workaround. A fix would be to adjust the threading to handle this new  Twitter behavior.

**Comment by PrivacyDevel** [comment]
This issue seems to have been solved: https://github.com/zedeus/nitter/issues/893#issuecomment-1647108842
